# Generated by Django 6.0.6 on 2026-07-02 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Non-UP Contractual', max_length=100)),
                ('rate_type', models.CharField(choices=[('DAILY', 'Daily Rate COS'), ('MONTHLY', 'Monthly Rate COS')], default='MONTHLY', max_length=10)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('terms_of_reference', models.FileField(blank=True, null=True, upload_to='contracts/tor/')),
                ('authority_to_hire', models.FileField(blank=True, null=True, upload_to='contracts/ath/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tin', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(default='LBP', max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(default='SPMO-S', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DisbursementVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dv_number', models.CharField(max_length=100, unique=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('requesting_unit', models.CharField(default='SYSTEM SUPPLY AND PROPERTY MANAGEMENT OFFICE (SPMO-S)', max_length=100)),
                ('expense_class', models.CharField(default='MOOE', max_length=50)),
                ('bank', models.CharField(default='Land Bank of the Philippines', max_length=100)),
                ('payment_option', models.CharField(default='ATM (ADA)', max_length=50)),
                ('request_category', models.CharField(default='c/o Unit', max_length=50)),
                ('status', models.CharField(choices=[('DRAFTED', 'Drafted'), ('WAITING_OBR', 'Waiting for the Approval of ObR/BUR'), ('UNIT_HEAD_APPROVED', 'Approved by Unit Head (Unit Head)'), ('SAO_RECEIVED', 'Hardcopies Received by SAO'), ('SAO_PRE_AUDIT', 'Checked by SAO Pre-Audit Staff'), ('SAO_SUPERVISOR', 'Checked by SAO Supervisor'), ('CASH_MONITORED', 'Released Cash Monitoring'), ('SAO_DIRECTOR', 'Approved by SAO Director'), ('APPROVED', 'APPROVED'), ('RADA_DRAFT', 'DRAFT (RADA)')], default='DRAFTED', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('check_ada_no', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_bank_account', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dvs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DVPayeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.TextField()),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('withholding_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_to_debit', models.CharField(default='SA03010001 (GF) -- SPMO-SUPS Supply and Property Management Office (SPMO) - 106510A / SA03010001', max_length=200)),
                ('expense_subclass', models.CharField(default='Regular MOOE/ Other General Services (Non-UP)', max_length=100)),
                ('ppa', models.CharField(default='A.I.a - 100000100001000', max_length=100)),
                ('is_contract_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.contract')),
                ('dv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payee_details', to='payroll.disbursementvoucher')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payees', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='payroll.employee'),
        ),
        migrations.CreateModel(
            name='ObligationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obr_number', models.CharField(max_length=100, unique=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('requesting_unit', models.CharField(default='SYSTEM SUPPLY AND PROPERTY MANAGEMENT OFFICE (SPMO-S)', max_length=100)),
                ('expense_class', models.CharField(default='MOOE', max_length=50)),
                ('fund_cluster', models.CharField(default='01 101101', max_length=100)),
                ('bank', models.CharField(default='Land Bank of the Philippines', max_length=100)),
                ('payment_option', models.CharField(default='ATM (ADA)', max_length=50)),
                ('request_category', models.CharField(default='c/o Unit', max_length=50)),
                ('status', models.CharField(choices=[('DRAFTED', 'Drafted'), ('SUBMITTED', 'Created/Submitted'), ('UNIT_HEAD_APPROVED', 'Approved by Unit Head'), ('SBO_OFFICER_REVIEWED', 'Reviewed by SBO Officer'), ('SBO_SUPERVISOR_REVIEWED', 'Reviewed by SBO Supervisor'), ('APPROVED', 'APPROVED')], default='DRAFTED', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_obrs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='disbursementvoucher',
            name='obr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvs', to='payroll.obligationrequest'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('UNIT_AO', 'Unit AO'), ('UNIT_HEAD', 'Unit Head'), ('SBO_STAFF', 'SBO Staff (Budget)'), ('SAO_RECEIVING', 'SAO Receiving'), ('SAO_PREAUDIT', 'SAO Pre-Audit'), ('SAO_PAYROLLSUP', 'SAO Payroll Supervisor'), ('SAO_CASHMONI', 'SAO Cash Monitoring'), ('SAO_DIRECTOR', 'SAO Director'), ('OVPA_VP', 'VP OVPA'), ('SCO_STAFF', 'SCO Staff (Cash Office)')], default='UNIT_AO', max_length=20)),
                ('unit_code', models.CharField(default='SPMO-S', max_length=20)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(blank=True, max_length=50)),
                ('status_to', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='payroll.disbursementvoucher')),
                ('obr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='payroll.obligationrequest')),
            ],
        ),
    ]
