# Generated by Django 6.0.6 on 2026-07-02 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employee_department_userprofile_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_name', models.CharField(default='UP System ICS Payroll Semi Mo', max_length=200)),
                ('department', models.CharField(choices=[('CIDS', 'Center For Integrative Development Studies (CIDS)'), ('CWGS', 'Center For Women And Gender Studies (CWGS)'), ('CIFAL', 'Centre International de Formation des Autorités et Leaders (CIFAL)'), ('COA', 'Commission on Audit (COA-System)'), ('ITDC', 'Information Technology Development Center (ITDC)'), ('MPRO', 'Media and Public Relation (MPRO)'), ('OVPDX', 'Office Of The Vice President For Digital Transformation (OVPDX)'), ('OAD', 'Office of Admissions (OAD)'), ('OAR', 'Office of Alumni Relations (OAR)'), ('ODPI', 'Office of Design and Planning Initiatives (ODPI)'), ('OIL', 'Office of International Linkages (OIL)'), ('OSR', 'Office of Sectoral Regents (OSR)'), ('OP', 'Office of the President (OP)'), ('OVPAA', 'Office of the Vice President for Academic Affairs (OVPAA)'), ('OVPA', 'Office of the Vice President for Administration (OVPA)'), ('OVPA_ISO', 'Office of the Vice President for Administration (OVPA-ISO)'), ('OVPD', 'Office of the Vice President for Development (OVPD)'), ('OVPLA', 'Office of the Vice President for Legal Affairs (OVPLA)'), ('OVPPF', 'Office of the Vice President for Planning and Finance (OVPPF)'), ('OVPRI', 'Office of the Vice President for Research and Innovation (OVPRI)'), ('PADAYON', 'Padayon Public Service Office'), ('PGC', 'Philippine Genome Center (PGC)'), ('PMO', 'Project Management Office (PMO)'), ('SAO', 'System Accounting Office (SAO)'), ('SCO', 'System Cash Office (SCO)'), ('SHRDO', 'System Human Resource Development Office (SHRDO)'), ('SPO', 'System Procurement Office (SPO)'), ('SSPMO', 'System Supply and Property Management Office (SSPMO)'), ('TVUP', 'TVUP (TVUP)'), ('UPBGC', 'UP Bonifacio Global City Campus (UPBGC)'), ('ISC', 'UP Intelligent Systems Center (ISC)'), ('KRC', 'UP Korea Research Center (KRC)'), ('PRESS', 'UP Press'), ('UPRI', 'UP Resilience Institute (UPRI)'), ('PAHINUNGOD', 'UP Ugnayan Ng Pahinungod Office')], default='SSPMO', max_length=100)),
                ('fund', models.CharField(default='101', max_length=50)),
                ('bank', models.CharField(default='LBP', max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralPayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_basis', models.DecimalField(decimal_places=2, max_digits=12)),
                ('no_of_days', models.DecimalField(decimal_places=2, default=11.0, max_digits=5)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('philhealth_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sss', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('nvat_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ewt_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ewt_10', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('general_payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.generalpayroll')),
            ],
        ),
    ]
