# Generated by Django 6.0.6 on 2026-07-02 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_generalpayroll_generalpayrollitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementvoucher',
            name='general_payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvs', to='payroll.generalpayroll'),
        ),
    ]
