# Generated by Django 6.0.6 on 2026-07-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_disbursementvoucher_general_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='duties',
            field=models.TextField(blank=True, default='Perform general administrative functions.'),
        ),
        migrations.AddField(
            model_name='contract',
            name='funding_source',
            field=models.CharField(default='UPS SPMO MOOE', max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='head_of_unit_id',
            field=models.CharField(default='NO4-03-000009', max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='head_of_unit_id_details',
            field=models.CharField(default='June 8, 2022 / Quezon City', max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='head_of_unit_name',
            field=models.CharField(default='ISAGANI L. BAGUS', max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='head_of_unit_position',
            field=models.CharField(default='Acting Chief SSPMO', max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='witness1_name',
            field=models.CharField(default='MARK JOSHUA M. PEDROSA', max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='witness1_position',
            field=models.CharField(default='Administrative Assistant I', max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='witness2_name',
            field=models.CharField(default='JULIUS MAR L. DELA CRUZ', max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='witness2_position',
            field=models.CharField(default='Junior Office Manager', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='govt_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='govt_id_details',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
