# Generated by Django 5.0.14 on 2026-07-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_number', models.CharField(help_text='e.g. Memo No. ACR 26-100', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text="A short summary of the memo's contents")),
                ('file', models.FileField(help_text='Upload the PDF document', upload_to='memos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='disbursementvoucher',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='disbursementvoucher',
            name='status',
            field=models.CharField(choices=[('DRAFTED', 'Drafted'), ('WAITING_OBR', 'Waiting for the Approval of ObR/BUR'), ('UNIT_HEAD_APPROVED', 'Approved by Unit Head (Unit Head)'), ('SAO_RECEIVED', 'Received by SAO'), ('SAO_PRE_AUDIT', 'Checked by SAO Pre-Audit Staff'), ('SAO_SUPERVISOR', 'Checked by SAO Supervisor'), ('CASH_MONITORED', 'Released Cash Monitoring'), ('SAO_DIRECTOR', 'Approved by SAO Director'), ('APPROVED', 'APPROVED'), ('RADA_DRAFT', 'DRAFT (RADA)')], default='DRAFTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='dvpayeedetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalpayroll',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalpayrollitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='obligationrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
